#### Task 1
- Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Task 2
- Создать 5 двумерных массивов разной формы из массива a. 
- Не использовать в аргументах метода reshape число -1.


In [5]:
a1 = np.reshape(a, (3, 4))
a2 = np.resize(a, (4, 3))
a3 = np.resize(a, (2, 6))
a4 = np.resize(a, (12, 1))
a5 = np.resize(a, (6, 2))
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

#### Task 3
- Создать 5 двумерных массивов разной формы из массива a. 
- Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [6]:
a1 = np.reshape(a, (2, -1))
a2 = np.reshape(a, (3, -1))
a3 = np.reshape(a, (4, -1))
a4 = np.reshape(a, (-1, 2))
a5 = np.reshape(a, (-1, 4))
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

#### Task 4
- Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [7]:
np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12]]).shape

(12, 1)

Массив назвать одномерным нельзя, так как для доступа к ячейке требуется две координаты.

#### Task 5
- Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
- Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [8]:
rand_a = np.random.randn(3, 4)
rand_a, rand_a.size

(array([[ 2.54267212,  0.1932531 ,  0.93142071,  0.42320092],
        [-0.11422199, -0.70867933, -1.75763564, -0.00968638],
        [ 0.24656914,  0.67120586, -0.4387993 , -0.70354908]]),
 12)

In [9]:
rand_a.reshape(12).size

12

#### Task 6
- Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [10]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Task 7
- Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
- В чем разница между массивами a и b?


In [11]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [12]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Разницы между массивами - нет.

#### Task 8
- Вертикально соединить массивы a и b. 
- a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. 
- Итоговый массив v должен иметь атрибут size, равный 10.


In [61]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
c.size

10

#### Task 9
- Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
- Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
- Получить матрицу At путем транспонирования матрицы A. 
- Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
- Какой размер имеет матрица B? 
- Получится ли вычислить обратную матрицу для матрицы B и почему?


In [17]:
A = np.arange(0, 12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
A = A.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
AT = A.T
AT

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [20]:
B = A @ AT
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [21]:
B.shape, np.linalg.det(B)

((4, 4), 0.0)

Обратную матрицу найти не получится, так как определитель матрицы B равен 0. 

#### Task 10
- Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [22]:
np.random.seed(42)

#### Task 11
- Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [23]:
C = np.random.randint(0, 16, (1, 16))
C

array([[ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4]])

#### Task 12
- Поменяйте его форму так, чтобы получилась квадратная матрица C. 
- Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
- Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [24]:
C = C.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [25]:
D = 10 * C + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [26]:
det_D = np.linalg.det(D)
rang_D = np.linalg.matrix_rank(D)
inv_D = np.linalg.inv(D)
print(f'Определитель матрицы D = {det_D};\nРанг матрицы D = {rang_D};\nОбратная матрица:\n{inv_D}')

Определитель матрицы D = -28511999.999999944;
Ранг матрицы D = 4;
Обратная матрица:
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


#### Task 13
- Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
- Убедитесь, что в матрице D_inv остались только нули и единицы. 
- С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
- Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, 
- а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [27]:
inv_D[inv_D > 0] = 1
inv_D[inv_D < 0] = 0
inv_D

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [28]:
E = np.where(inv_D, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])